apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-my-pv
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.capacity.storage }}
  accessModes:
    - {{ .Values.accessModes }}
  hostPath:
    path: {{ .Values.hostPath.path }}
