apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-my-service
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
     