spec:
  replicas: 2
 
app: nextjs-app

name: nextjs-app

containers:
  image: nextjs-app:1.0.0
  name: nextjs-app

secretRef:
  name: mysecret

configMapRef:
  name: db

tolerations:
  key: Assignment
  operator: Exists
  effect: NoSchedule
