apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app }}
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
      - image: {{ .Values.containers.images }}
        name: {{ .Values.containers.name }}
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
        envFrom:
        - secretRef:
            name: {{ .Values.secretRef.name }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMapRef.name }}
      tolerations:
      - key: {{ .Values.tolerations.key }}
        operator: {{ .Values.tolerations.operator }}
        effect: {{ .Values.tolerations.effect }}
status: {}
