spec:
  replicas: 2
  
app: nextjs-app

name: nextjs-app

containers:
  image: nextjs-app:1.0.0
  name: nextjs-app

secretRef:
  name: mysecret

configMapRef:
  name: db

tolerations:
  key: Assignment
  operator: Exists
  effect: NoSchedule

ports:
  port: 8901
  targetPort: 80


storageClassName: manual

capacity:
    storage: 2Gi

resources:
    requests:
      storage: 2Gi


accessModes:
    ReadWriteOnce

hostPath:
    path: "/mnt/data"